### ISSUE TITLE
In-game mod browser downloads incorrect version

### ISSUE THREAD

**Issue by Xeneonic** [raiguard/Factorio-Flib#51] opened 2023-04-01 09:06 UTC
I'll just leave this here, since Raiguard doesn't always check Discord.

![image](https://user-images.githubusercontent.com/7692702/229276775-bfab8e79-6cfc-45f3-83c2-5792470518f0.png)

**Comment by Xeneonic** [comment] 2023-04-01 09:25
Issue is solved by updating factorio to a later version. That said, the factorio version I was running (1.1.72) should have allowed the in-game mod browser to update it to 0.12.0 as 1.1.74 is an optional dependency there. Thanks to SpeckledFleebeedoo on the official factorio discord for figuring that one out for me.

![image](https://user-images.githubusercontent.com/7692702/229277838-0ec639e9-f2fc-4d88-8399-b8f60dea8c4f.png)

**Comment by raiguard** [comment] 2023-04-15 21:38
Yeah, this was caused by the dependency being optional, which I fixed in 0.12.3.

**Closed as not planned by raiguard** 2023-04-15 21:38 UTC
